# Generated by Django 2.2.19 on 2023-10-09 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Menu description')),
            ],
            options={
                'verbose_name': 'Menu',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Title')),
                ('url', models.URLField(max_length=300, verbose_name='Url')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Position')),
                ('item_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Menu.MenuItem', verbose_name='Item parent')),
                ('menu_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.Menu', verbose_name='Menu')),
            ],
            options={
                'verbose_name': 'Menu item',
                'ordering': ['menu_parent', 'position'],
            },
        ),
    ]
