# Generated by Django 2.2.19 on 2023-10-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['name'], 'verbose_name': 'Menu'},
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='description',
            new_name='name',
        ),
    ]
