# Generated by Django 2.2.19 on 2023-10-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_auto_20231010_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Menu name'),
        ),
    ]
